#Vagrant API
VAGRANTFILE_API_VERSION = '2'
IPSTART = 10
VNETWORK = "192.168.60."
NODESNUMBER = 2
VCLUSTERIPS = Array.new
i = 1
VWEBIP = "192.168.60.#"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   # General config
   config.vm.box = "generic/centos9s"
   config.ssh.insert_key = false
   config.vm.provider :virtualbox do |v|
     v.memory = 1560
     v.linked_clone = true
   end


   # Loop until all VMs specified in NODESNUMBER are created
  (i..NODESNUMBER).each do |machine_id|
      config.vm.define "dbnode#{machine_id}" do |machine|
        machine.vm.hostname = "dbnode#{machine_id}"
        machine.vm.network "private_network", ip: "#{VNETWORK}#{IPSTART + machine_id}"
        VCLUSTERIPS.append("#{VNETWORK}#{IPSTART + machine_id}") 
   
        # When it's done start Ansible provisioning
   if machine_id == NODESNUMBER
      machine.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.playbook = "../site.yml"
      ansible.extra_vars = {
        clusterips: VCLUSTERIPS,
        webip: VWEBIP
       }
      ansible.groups = {
        "cluster" => ["dbnode[1:#{NODESNUMBER}]"]
      }
       end
      end
    end
  end
end



