---     
      - name: install Mariadb
        yum: name={{ item }} state=present
        with_items:
         - mariadb-server
         - python3-mysqlclient

      - name: Start and enable mariadb server
        ansible.builtin.service:
         name: mariadb
         state: started
         enabled: yes

      - name: Initialize mariadb root
        community.mysql.mysql_user:
         login_user: root
         login_password: "{{mariadbroot}}"
         check_implicit_admin: true
         name: root
         password: "{{mariadbroot}}"

      - name: Copy my.cfn to host
        ansible.builtin.template:
         src: ../templates/ansible.cnf.j2
         dest: /etc/my.cnf.d/ansible.cnf
         owner: root
         group: root
         mode: '0644'
        notify:
        - Restart mariadb
